easy_admin:
    site_name: '<img src="" /> E.D.S'
    design:
        brand_color: '#c9046b'
        color_scheme: 'light'
        form_theme: 'vertical'

    list:
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'remove', label: ''}