services:
#    planning.example:
#        class: PlanningBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    planning.service.time:
        class: PlanningBundle\Service\Time