migrations_directory: "/Applications/MAMP/htdocs/Planning-Atelier-Acces-Sit/app/DoctrineMigrations2"
migrations_namespace: Application\Migrations
table_name: migration_versions
name: Application Migrations

