sql_srv:
    resource: "@SqlSrvBundle/Controller/"
    type:     annotation
    prefix:   /

planning:
    resource: "@PlanningBundle/Controller/"
    type:     annotation
    prefix:   /

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin