ben:
    resource: "@BenBundle/Controller/"
    type:     annotation
    prefix:   /

sql_srv:
    resource: "@SqlSrvBundle/Controller/"
    type:     annotation
    prefix:   /

planning:
    resource: "@PlanningBundle/Controller/"
    type:     annotation
    prefix:   /

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"