# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/PlanningBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    PlanningBundle\:
        resource: '../../src/PlanningBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/PlanningBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    PlanningBundle\Controller\:
        resource: '../../src/PlanningBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    planning.entity.calendar_event:
        class: PlanningBundle\Listener\LoadDataListener
#        arguments: ['mois'    , new \]
        tags:
                - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: 'loadData' }

    app.security.login_form_authenticator:
        class: PlanningBundle\Security\LoginFormAuthenticator
        autowire: true

    app.doctrine.hash_password_listener:
            class: PlanningBundle\Listener\HashPasswordListener
            autowire: true
            tags:
                - { name: doctrine.event_subscriber }

    # add more services, or override services that need manual wiring
    # PlanningBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

