easy_admin:
    entities:
        Actor:
            class: PlanningBundle\Entity\Main\Actor
            list:
                title: "Actors Workshops"
                fields:
                    - name
                    - enabled

            form:
                fields:
                    - { type: 'tab' , label: 'Information', icon: 'user' }
                    - name
                    - enabled

            new:
                title:  'Ajouter un nouvel acteur'
                form_options: { validation_groups: ['Default', 'Actor'] }

            edit:
                title:  "Modifier l'Acteur"
                form_options: { validation_groups: ['Default', 'Actor'] }

            show:
                title:  "Acteur"
                form_options: { validation_groups: ['Default', 'Actor'] }


