easy_admin:
    entities:
        Actor:
            class: PlanningBundle\Entity\Main\Actor
            list:
                title: "Actors Workshops"
                fields:
                    - enabled
                    - name
                    - competence

            form:
                fields:
                    - { type: 'group' , label: 'Information', css_class: 'col-sm-6', icon: 'user' }
#                    - id
                    - name
                    - enabled
                    - { type: 'group', label: 'Tasks', css_class: 'col-sm-6', icon: 'tasks' }
                    - competence
                    - { property: 'deg', type: 'PlanningBundle\Form\Type\DegType' }

            new:
                title:  'Ajouter un nouvel acteur'
                form_options: { validation_groups: ['Default', 'Actor'] }

            edit:
                title:  "Modifier l'Acteur"
                form_options: { validation_groups: ['Default', 'Actor'] }

            show:
                title:  "Acteur"
                fileds:
                    - competence
                form_options: { validation_groups: ['Default', 'Actor'] }



