easy_admin:
    entities:
        Competence:
            class: PlanningBundle\Entity\Main\Competence
            form_theme: 'vertical'
            list:
                title: "List of Competence"
                fields:
                    - name
                    - actor
                    - position
            form:
                fields:
                    - { type: 'group' , label: 'Information', css_class: 'col-sm-6', icon: 'user' }
                    - name
                    - { type: 'group', label: 'Position', css_class: 'col-sm-6', icon: 'position' }
                    - position

            new:
                title:  'Ajouter une nouvelle Compétence'
                form_options: { validation_groups: ['Default', 'Competence'] }

            edit:
                title:  "Modifier la Compétence"
                fileds:
                    - position
                form_options: { validation_groups: ['Default', 'Competence'] }

            show:
                title: "Compétence"
                fields:
                    - position

