easy_admin:
    entities:
        User:
            class: PlanningBundle\Entity\Main\User
            list:
                title: "Authorized Administrator"
                fields:
                    - username
#                    - password

            form:
                fields:
                    - username
#                    - { property: 'roles', type: 'collection' }

                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { type: 'divider' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            edit:
                title: "Modifier l'Administrateur"
                fields:
                - { property: 'plainPassword', type: 'text', type_options: { required: true } }
            form_options: { validation_groups: ['Profile', 'User'] }

            new:
                title: "Ajouter un Administrateur"
                fields:
                    - { property: 'plainPassword', type_options: { required: true } }
                form_options: { validation_groups: ['Registration'] }

