easy_admin:
    entities:
        User:
            class: PlanningBundle\Entity\Main\User
            list:
                fields:
                    - username
                    - password
            form:
                fields:
                    - username
                    - password
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            edit:
                - { property: 'plainPassword', type: 'text', type_options: { required: true } }
            form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - { property: 'plainPassword', type_options: { required: true } }
                form_options: { validation_groups: ['Registration'] }